// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingEvents.Models;

namespace TrackingEvents.Migrations
{
    [DbContext(typeof(TrackingEventsContext))]
    [Migration("20190203092623_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrackingEvents.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("eventDesc");

                    b.Property<string>("eventType");

                    b.Property<int?>("externalModuleId");

                    b.HasKey("Id");

                    b.HasIndex("externalModuleId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TrackingEvents.Models.PainDiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("eventDate");

                    b.Property<string>("eventName");

                    b.HasKey("Id");

                    b.ToTable("PainDiary");
                });

            modelBuilder.Entity("TrackingEvents.Models.Events", b =>
                {
                    b.HasOne("TrackingEvents.Models.PainDiary", "externalModule")
                        .WithMany()
                        .HasForeignKey("externalModuleId");
                });
#pragma warning restore 612, 618
        }
    }
}
